package com.gov.internship.model;

public class Internship {

    private int internshipId;   // auto-generated by DB
    private String internName;
    private String email;
    private String domain;
    private int duration;

    // Constructor WITHOUT ID
    public Internship(String internName, String email, String domain, int duration) {
        this.internName = internName;
        this.email = email;
        this.domain = domain;
        this.duration = duration;
    }

    // ----- GETTERS & SETTERS -----

    public int getInternshipId() {
        return internshipId;
    }

    public void setInternshipId(int internshipId) {
        this.internshipId = internshipId;
    }

    public String getInternName() {
        return internName;
    }

    public String getEmail() {
        return email;
    }

    // 🔴 THESE TWO WERE MISSING (CAUSE OF ERROR)
    public String getDomain() {
        return domain;
    }

    public int getDuration() {
        return duration;
    }
}
